# Generated by Django 5.2.6 on 2025-09-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.botuser'),
        ),
        migrations.AddField(
            model_name='theme',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='content.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='theme',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='themes', to='content.type', verbose_name='Типы контента'),
        ),
        migrations.AddField(
            model_name='contentfile',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='files', to='content.type', verbose_name='Типы контента'),
        ),
        migrations.AddField(
            model_name='category',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='categories', to='content.type', verbose_name='Типы контента'),
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('category', 'slug')},
        ),
    ]
