# Generated by Django 5.2.6 on 2025-09-28 14:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'content path',
                'verbose_name_plural': 'Content paths',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['category', 'name'],
                'default_related_name': 'topics',
            },
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='theme',
            name='category',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='types',
        ),
        migrations.RemoveField(
            model_name='category',
            name='types',
        ),
        migrations.RemoveField(
            model_name='contentfile',
            name='types',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contentfile',
            options={'default_related_name': 'files', 'ordering': ['name', 'file_type'], 'verbose_name': 'file', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='contentrating',
            options={'default_related_name': 'ratings', 'ordering': ['created_at', 'content', 'rating', 'user'], 'verbose_name': 'user rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AddField(
            model_name='contentfile',
            name='categories',
            field=models.ManyToManyField(to='content.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='file',
            field=models.FileField(upload_to='content/files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF document'), ('IMAGE', 'Image'), ('TEXT', 'Text file'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('OTHER', 'Other file type')], max_length=10, verbose_name='File type'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='contentrating',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contentfile', verbose_name='Content unit'),
        ),
        migrations.AlterField(
            model_name='contentrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='contentrating',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Allowed rating: from 1 to 5.'), django.core.validators.MaxValueValidator(5, 'Allowed rating: from 1 to 5.')], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='contentrating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.botuser', verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='contentrating',
            constraint=models.UniqueConstraint(fields=('content', 'user'), name='unique_user_rating'),
        ),
        migrations.AddField(
            model_name='contentfile',
            name='paths',
            field=models.ManyToManyField(blank=True, to='content.path', verbose_name='Content paths'),
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='topic',
            name='paths',
            field=models.ManyToManyField(blank=True, to='content.path', verbose_name='Content paths'),
        ),
        migrations.AddField(
            model_name='contentfile',
            name='topics',
            field=models.ManyToManyField(to='content.topic', verbose_name='Topics'),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
