# Generated by Django 5.2.6 on 2025-09-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_path_topic_alter_theme_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'default_related_name': 'topics', 'ordering': ['name'], 'verbose_name': 'topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='paths',
        ),
    ]
