# Generated by Django 5.2.6 on 2025-09-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_topic_options_remove_topic_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='topics',
            field=models.ManyToManyField(blank=True, to='content.topic', verbose_name='Topics'),
        ),
    ]
