# Generated by Django 5.2.6 on 2025-09-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_contentfile_topics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
