# Generated by Django 5.2.6 on 2025-09-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_category_slug_alter_path_slug_alter_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfile',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF document'), ('IMAGE', 'Image'), ('TEXT', 'Text file'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('OTHER', 'Other file type')], max_length=100, verbose_name='File type'),
        ),
    ]
