# Generated by Django 5.2.6 on 2025-10-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_botmessage'),
        ('users', '0003_alter_botuser_options_alter_staffuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='ContentViewStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='viewing time')),
                ('content_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_stats', to='content.contentfile', verbose_name='file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_views', to='users.botuser', verbose_name='bot user')),
            ],
            options={
                'verbose_name': 'viewing statistics',
                'verbose_name_plural': 'Viewing statistics',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='content_con_user_id_6c6a50_idx'), models.Index(fields=['content_file', 'viewed_at'], name='content_con_content_47ab89_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_file', 'viewed_at'), name='unique_user_content_view')],
            },
        ),
    ]
