# Generated by Django 5.2.6 on 2025-10-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_botmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
