# Generated by Django 5.2.6 on 2025-10-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_contentfile_is_active_contentviewstat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotMessage',
        ),
    ]
