# Generated by Django 5.2.6 on 2025-10-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_contentfile_is_active'),
        ('content', '0011_delete_botmessage'),
    ]

    operations = [
    ]
