# Generated by Django 5.2.6 on 2025-10-02 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_merge_20251002_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='content.path'),
        ),
    ]
