# Generated by Django 5.2.6 on 2025-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_category_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='path',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Slug'),
        ),
    ]
