# Generated by Django 5.2.6 on 2025-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_category_slug_alter_path_slug_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=15, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='path',
            name='slug',
            field=models.SlugField(max_length=15, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=15, unique=True, verbose_name='Slug'),
        ),
    ]
