# Generated by Django 5.2.6 on 2025-12-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_category_slug_alter_path_slug_alter_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfile',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='content/files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF document'), ('IMAGE', 'Image'), ('TEXT', 'Text file'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('OTHER', 'Other file type'), ('LINK', 'External link')], max_length=100, verbose_name='File type'),
        ),
    ]
