MAX_FILENAME_CHARS = 10
MAX_NAME_CHARS = 200
MAX_SLUG_CHARS = 100

MIN_RATING_INT = 1
MAX_RATING_INT = 5
RATING_VALIDATION_ERROR = (
    f'Allowed rating: from {MIN_RATING_INT} to {MAX_RATING_INT}.'
)

MAX_OBJECT_CHARS = 50  # For Django Admin page display
