# Generated by Django 5.2.6 on 2025-09-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='username',
            field=models.CharField(),
        ),
    ]
