# Generated by Django 5.2.6 on 2025-09-29 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_staffuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'bot user', 'verbose_name_plural': 'Bot users'},
        ),
        migrations.AlterModelOptions(
            name='staffuser',
            options={'verbose_name': 'Staff user', 'verbose_name_plural': 'Staff users'},
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sign-up date'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last active'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, null=True, verbose_name='Username'),
        ),
    ]
