# Generated by Django 5.2.6 on 2025-10-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_botuser_options_alter_staffuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, null=True, verbose_name='First name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sign-up date')),
            ],
            options={
                'verbose_name': 'stat bot user',
                'verbose_name_plural': 'Stat bot users',
            },
        ),
    ]
