# Generated by Django 5.2.6 on 2025-10-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='message key')),
                ('text', models.TextField(verbose_name='message text')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='comment')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
            ],
            options={
                'verbose_name': 'bot message',
                'verbose_name_plural': 'Bot messages',
                'ordering': ['key'],
            },
        ),
    ]
